"""Render README.md (short, plain language) and TECHNICAL_REPORT.md (the full report) from
their templates in docs/readme/, so every number in either comes from a committed results
file. The rendered documents are never edited by hand.

The templates hold the prose. Numbers are placeholders:
  {{name}}         a value defined in docs/readme/values.yaml: a results file (a path under
                   results/), a path inside it (`/`-separated, since keys contain dots) and a
                   format; or an `expr` over other values; or `pending: true`, which renders
                   TBD until the result exists. A missing results file is otherwise an error,
                   so a typo cannot quietly turn into TBD.
  {{table:name}}   a table built below from results files, ending with its source line
Checks, in both modes:
  - no decimal or percentage typed into a template outside a placeholder, unless
    values.yaml allows it (version numbers, such as a model's);
  - every table in either document is followed by a `Source:` line saying where its
    content comes from.
Modes:
  (default)   write README.md and TECHNICAL_REPORT.md
  --check     render in memory and fail if either file differs from a fresh render (a hand
              edit, or a results file changed without a re-render). CI runs this.

Usage:
    uv run python scripts/90_readme.py
    uv run python scripts/90_readme.py --check
"""

from __future__ import annotations

import argparse
import ast
import json
import operator
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
# (template, output): both share docs/readme/values.yaml and the tables below
DOCS = [
    (ROOT / "docs/readme/README.template.md", ROOT / "README.md"),
    (ROOT / "docs/readme/TECHNICAL_REPORT.template.md", ROOT / "TECHNICAL_REPORT.md"),
]
VALUES = ROOT / "docs/readme/values.yaml"
RESULTS = ROOT / "results"
PLACEHOLDER = re.compile(r"\{\{\s*([\w.:-]+)\s*\}\}")
# a decimal or a percentage typed into the prose (integers are left to review: years and
# counts in prose are not results)
LITERAL = re.compile(r"(?<![\w.-])\d+\.\d+(?![\w.])|(?<![\w.-])\d+(?:\.\d+)?\s?%")
TABLE_ROW = re.compile(r"^\s*\|")
SOURCE_LINE = re.compile(r"Source:\s*[^\s<]")  # names something, not just a closing tag
TBD = "TBD"
HEADER = "<!-- Generated by scripts/90_readme.py from docs/readme/; edit those, not this. -->\n"

_files: dict[str, Any] = {}


def load(rel: str) -> Any:
    """A results file, by its path under results/ (JSON, or JSONL as a list)."""
    if rel not in _files:
        text = (RESULTS / rel).read_text(encoding="utf-8")
        if rel.endswith(".jsonl"):
            _files[rel] = [json.loads(x) for x in text.splitlines() if x]
        else:
            _files[rel] = json.loads(text)
    return _files[rel]


def lookup(obj: Any, path: str) -> Any:
    for part in path.split("/") if path else []:
        if isinstance(obj, list):
            obj = obj[int(part)]
        else:
            if part not in obj:
                raise KeyError(f"no {part!r} in path {path!r}")
            obj = obj[part]
    return obj


# --------------------------------------------------------------------------------------
# Formats


def _num(x: float, digits: int) -> str:
    s = f"{x:.{digits}f}"
    return s.replace("-", "−") if s.startswith("-") and float(s) != 0 else s.lstrip("-")


def _duration(s: float) -> str:
    if s >= 5400:
        return f"{s / 3600:.1f} h"
    return f"{s / 60:.0f} min" if s >= 90 else f"{s:.0f} s"


def fmt(value: Any, spec: str) -> str:
    """f3 -> 0.179 | sf2 -> +0.04 | pct1 -> 17.9% | pp1 -> +1.2 pp | ppci1 -> [−1.0, +1.7] |
    int -> 1,234 | usd2 -> $0.62 | dur -> 1.7 h | ci2 -> [0.27, 0.75] |
    pm3 -> 0.080 ± 0.012 (a spread) | s1 -> seconds with one decimal | str"""
    kind, digits = re.fullmatch(r"([a-z]+)(\d*)", spec).groups()
    d = int(digits) if digits else 0
    if kind == "str":
        return str(value)
    if kind == "int":
        return f"{int(round(value)):,}"
    if kind == "f":
        return _num(value, d)
    if kind == "sf":  # signed: a difference
        s = _num(value, d)
        return f"+{s}" if round(value, d) > 0 else s
    if kind == "pct":
        return f"{_num(100 * value, d)}%"
    if kind == "pp":
        s = _num(100 * value, d)
        return f"{'+' if round(100 * value, d) > 0 else ''}{s} pp"
    if kind == "usd":
        return f"${value:,.{d}f}"
    if kind == "ci":
        return f"[{_num(value[0], d)}, {_num(value[1], d)}]"
    if kind == "ppci":  # an interval of a difference, in percentage points
        lo, hi = (fmt(v, f"pp{d}").removesuffix(" pp") for v in value)
        return f"[{lo}, {hi}]"
    if kind == "pm":
        return f"{_num(value['mean'], d)} ± {_num(value['std'], d)}"
    if kind == "s":
        return f"{value:.{d}f} s"
    if kind == "dur":  # a duration in seconds, in the unit that reads best
        return _duration(value)
    raise ValueError(f"unknown format {spec!r}")


# --------------------------------------------------------------------------------------
# Values

_OPS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.USub: operator.neg,
}
NAME = re.compile(r"[A-Za-z_][\w.]*")


def _eval(expr: str, env: dict[str, float]) -> float:
    """Arithmetic over named values only: + - * / and parentheses."""

    def walk(n: ast.AST) -> float:
        if isinstance(n, ast.Expression):
            return walk(n.body)
        if isinstance(n, ast.BinOp) and type(n.op) in _OPS:
            return _OPS[type(n.op)](walk(n.left), walk(n.right))
        if isinstance(n, ast.UnaryOp) and type(n.op) in _OPS:
            return _OPS[type(n.op)](walk(n.operand))
        if isinstance(n, ast.Constant) and isinstance(n.value, int | float):
            return n.value
        if isinstance(n, ast.Name):
            return env[n.id]
        raise ValueError(f"not allowed in expr: {ast.dump(n)}")

    return walk(ast.parse(expr.replace(".", "__"), mode="eval"))


def resolve_values(spec: dict) -> dict[str, str]:
    raw: dict[str, Any] = {}
    out: dict[str, str] = {}
    tbd: set[str] = set()  # pending values, and exprs over them
    todo = dict(spec.get("values") or {})
    while todo:
        progressed = False
        for name, v in list(todo.items()):
            if v.get("pending"):
                tbd.add(name)
            elif "expr" in v:
                deps = set(NAME.findall(v["expr"]))
                if not deps <= set(raw) | tbd:
                    continue
                if deps & tbd:
                    tbd.add(name)
                else:
                    env = {k.replace(".", "__"): raw[k] for k in deps}
                    raw[name] = _eval(v["expr"], env)
            elif "count_where" in v:  # items of a list (or values of a dict) matching all
                items = lookup(load(v["file"]), v["path"])
                items = items.values() if isinstance(items, dict) else items
                raw[name] = sum(
                    all(x.get(k) == want for k, want in v["count_where"].items()) for x in items
                )
            elif "sum_of" in v:  # sum of one field over a list, or a dict's values
                items = lookup(load(v["file"]), v["path"])
                items = items.values() if isinstance(items, dict) else items
                raw[name] = sum(lookup(x, v["sum_of"]) for x in items)
            elif "mean_of" in v:  # mean of one field over a list of records
                items = [lookup(x, v["mean_of"]) for x in lookup(load(v["file"]), v["path"])]
                raw[name] = sum(items) / len(items)
            else:
                raw[name] = lookup(load(v["file"]), v["path"])
            out[name] = TBD if name in tbd else fmt(raw[name], v["fmt"])
            del todo[name]
            progressed = True
        if not progressed:
            raise ValueError(f"unresolvable values (unknown names in expr?): {sorted(todo)}")
    return out


# --------------------------------------------------------------------------------------
# Tables: each a function returning Markdown built from results files, registered with
# @table and placed with {{table:<function name>}}.

TABLES: dict[str, Any] = {}


def table(fn):
    TABLES[fn.__name__] = fn
    return fn


def md(header: list[str], rows: list[list[str]], source: str) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines) + f"\n\n<sub>Source: {source}</sub>"


SECURITY_CATEGORIES = {
    "destructive": "Destructive statements",
    "multi_statement": "Several statements in one",
    "obfuscation": "Comment and unicode obfuscation",
    "catalog_snooping": "Catalog, file and network snooping",
    "confinement": "Another database's tables",
    "session": "Changing session settings",
    "resource_exhaustion": "Resource exhaustion",
    "prompt_injection": "What a planted instruction asks for",
}


@table
def security_suite() -> str:
    """Attacks per category, and how many each layer stopped on its own."""
    suite = load("metrics/security_suite.json")
    modes = ("parser", "database", "privileges")
    rows = []
    for key, label in SECURITY_CATEGORIES.items():
        recs = [r for r in suite["records"] if r["category"] == key]
        cells = []
        for mode in modes:
            outcomes = [r["modes"][mode]["outcome"] for r in recs]
            stopped = sum(o in ("rejected", "denied", "contained", "no_effect") for o in outcomes)
            shown = outcomes.count("disclosed")
            cells.append(f"{stopped}" + (f" (+{shown} names listed)" if shown else ""))
        rows.append([label, str(len(recs)), *cells])
    return md(
        [
            "Kind of attack",
            "Attacks",
            "Stopped by the checker alone",
            "By the database alone",
            "By the role's privileges alone",
        ],
        rows,
        "`results/metrics/security_suite.json` (one run)",
    )


# --------------------------------------------------------------------------------------
# Checks


def typed_literals(template: Path) -> list[str]:
    spec = yaml.safe_load(VALUES.read_text(encoding="utf-8"))
    allowed = set(spec.get("allowed_literals") or [])
    text = PLACEHOLDER.sub("", template.read_text(encoding="utf-8"))
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    text = re.sub(r"`[^`\n]*`", "", text)  # code spans: settings, versions, paths
    text = re.sub(r"\]\([^)]*\)", "]", text)  # link targets
    found = []
    for i, line in enumerate(text.splitlines(), 1):
        for m in LITERAL.finditer(line):
            if m.group(0) not in allowed:
                found.append(f"{template.name} line {i}: {m.group(0)!r} in: {line.strip()[:80]}")
    return found


def tables_without_source(text: str, name: str) -> list[str]:
    """Tables (runs of lines starting with `|`, outside code blocks) not followed, after
    any blank lines, by a line with `Source:` and something after it."""
    lines = text.splitlines()
    problems, i, in_code = [], 0, False
    while i < len(lines):
        if lines[i].lstrip().startswith("```"):
            in_code = not in_code
        elif not in_code and TABLE_ROW.match(lines[i]):
            start = i
            while i < len(lines) and TABLE_ROW.match(lines[i]):
                i += 1
            j = i
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j == len(lines) or not SOURCE_LINE.search(lines[j]):
                problems.append(f"{name} line {start + 1}: a table without a Source: line")
            continue
        i += 1
    return problems


# --------------------------------------------------------------------------------------


def render(template: Path, values: dict[str, str]) -> str:
    def sub(m: re.Match) -> str:
        name = m.group(1)
        if name.startswith("table:"):
            return TABLES[name.split(":", 1)[1]]()
        if name not in values:
            raise KeyError(f"{template.name}: {{{{{name}}}}} has no value in values.yaml")
        return values[name]

    return HEADER + PLACEHOLDER.sub(sub, template.read_text(encoding="utf-8"))


def render_all() -> dict[Path, str]:
    spec = yaml.safe_load(VALUES.read_text(encoding="utf-8"))
    values = resolve_values(spec)
    used = {n for t, _ in DOCS for n in PLACEHOLDER.findall(t.read_text(encoding="utf-8"))}
    in_exprs = {
        n for v in (spec.get("values") or {}).values() for n in NAME.findall(v.get("expr", ""))
    }
    unused = set(values) - used - in_exprs
    if unused:
        print(f"note: values defined but not used: {sorted(unused)}")
    pending = sorted(n for n, v in values.items() if v == TBD)
    if pending:
        print(f"note: {len(pending)} values pending (rendered TBD): {pending}")
    return {out: render(t, values) for t, out in DOCS}


def problems_in(rendered: dict[Path, str]) -> list[str]:
    found = [
        f"typed number (not from a results file): {x}" for t, _ in DOCS for x in typed_literals(t)
    ]
    found += [x for out, text in rendered.items() for x in tables_without_source(text, out.name)]
    return found


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_all()
    problems = problems_in(rendered)
    if args.check:
        problems += [
            f"{out.name} differs from a fresh render: run scripts/90_readme.py"
            for out, text in rendered.items()
            if not out.exists() or out.read_text(encoding="utf-8") != text
        ]
        if problems:
            sys.exit("\n".join(problems))
        print("README.md and TECHNICAL_REPORT.md match the results files")
        return
    if problems:
        sys.exit("\n".join(problems))
    for out, text in rendered.items():
        out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
