"""Render README.md (short, plain language) and TECHNICAL_REPORT.md (the full report) from
their templates in docs/readme/, so every number in either comes from a committed results
file. The rendered documents are never edited by hand.

The templates hold the prose. Numbers are placeholders:
  {{name}}         a value defined in docs/readme/values.yaml: a results file (a path under
                   results/), a path inside it (`/`-separated, since keys contain dots) and a
                   format; or an `expr` over other values; or `pending: true`, which renders
                   TBD until the result exists. A missing results file is otherwise an error,
                   so a typo cannot quietly turn into TBD.
  {{table:name}}   a table built below from results files, ending with its source line
Checks, in both modes:
  - no decimal or percentage typed into a template outside a placeholder, unless
    values.yaml allows it (version numbers, such as a model's);
  - every table in either document is followed by a `Source:` line saying where its
    content comes from.
Modes:
  (default)   write README.md and TECHNICAL_REPORT.md
  --check     render in memory and fail if either file differs from a fresh render (a hand
              edit, or a results file changed without a re-render). CI runs this.

Usage:
    uv run python scripts/90_readme.py
    uv run python scripts/90_readme.py --check
"""

from __future__ import annotations

import argparse
import ast
import json
import operator
import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parent.parent
# (template, output): both share docs/readme/values.yaml and the tables below
DOCS = [
    (ROOT / "docs/readme/README.template.md", ROOT / "README.md"),
    (ROOT / "docs/readme/TECHNICAL_REPORT.template.md", ROOT / "TECHNICAL_REPORT.md"),
]
VALUES = ROOT / "docs/readme/values.yaml"
RESULTS = ROOT / "results"
PLACEHOLDER = re.compile(r"\{\{\s*([\w.:-]+)\s*\}\}")
# a decimal or a percentage typed into the prose (integers are left to review: years and
# counts in prose are not results)
LITERAL = re.compile(r"(?<![\w.-])\d+\.\d+(?![\w.])|(?<![\w.-])\d+(?:\.\d+)?\s?%")
TABLE_ROW = re.compile(r"^\s*\|")
SOURCE_LINE = re.compile(r"Source:\s*[^\s<]")  # names something, not just a closing tag
TBD = "TBD"
HEADER = "<!-- Generated by scripts/90_readme.py from docs/readme/; edit those, not this. -->\n"

_files: dict[str, Any] = {}


def load(rel: str) -> Any:
    """A results file, by its path under results/ (JSON, or JSONL as a list)."""
    if rel not in _files:
        text = (RESULTS / rel).read_text(encoding="utf-8")
        if rel.endswith(".jsonl"):
            _files[rel] = [json.loads(x) for x in text.splitlines() if x]
        else:
            _files[rel] = json.loads(text)
    return _files[rel]


def lookup(obj: Any, path: str) -> Any:
    """`/`-separated; a key that itself contains `/` (a run named model/design) is matched by
    joining parts until a key is found."""
    parts = path.split("/") if path else []
    i = 0
    while i < len(parts):
        if isinstance(obj, list):
            obj = obj[int(parts[i])]
            i += 1
            continue
        for j in range(i + 1, len(parts) + 1):
            key = "/".join(parts[i:j])
            if key in obj:
                obj, i = obj[key], j
                break
        else:
            raise KeyError(f"no {parts[i]!r} in path {path!r}")
    return obj


# --------------------------------------------------------------------------------------
# Formats


def _num(x: float, digits: int) -> str:
    s = f"{x:.{digits}f}"
    return s.replace("-", "−") if s.startswith("-") and float(s) != 0 else s.lstrip("-")


def _duration(s: float) -> str:
    if s >= 5400:
        return f"{s / 3600:.1f} h"
    return f"{s / 60:.0f} min" if s >= 90 else f"{s:.0f} s"


def fmt(value: Any, spec: str) -> str:
    """f3 -> 0.179 | sf2 -> +0.04 | pct1 -> 17.9% | pp1 -> +1.2 pp | ppci1 -> [−1.0, +1.7] |
    int -> 1,234 | usd2 -> $0.62 | dur -> 1.7 h | ci2 -> [0.27, 0.75] | pctci1 -> [0.6, 2.8] |
    pm3 -> 0.080 ± 0.012 (a spread) | s1 -> seconds with one decimal | str
    An interval as the reports write it ({estimate, low, high}): pctiv1 -> [55.3, 65.9] (a
    share, in percent) | ppiv1 -> [+10.7, +24.0] (a difference, in points) | civ2 -> [0.71, 0.82]"""
    kind, digits = re.fullmatch(r"([a-z]+)(\d*)", spec).groups()
    d = int(digits) if digits else 0
    if kind in ("pctiv", "ppiv", "civ"):
        pair = [value["low"], value["high"]]
        if kind == "civ":
            return fmt(pair, f"ci{d}")
        if kind == "ppiv":
            return fmt(pair, f"ppci{d}")
        return f"[{_num(100 * pair[0], d)}, {_num(100 * pair[1], d)}]"
    if kind == "str":
        return str(value)
    if kind == "int":
        return f"{int(round(value)):,}"
    if kind == "f":
        return _num(value, d)
    if kind == "sf":  # signed: a difference
        s = _num(value, d)
        return f"+{s}" if round(value, d) > 0 else s
    if kind == "pct":
        return f"{_num(100 * value, d)}%"
    if kind == "pp":
        s = _num(100 * value, d)
        return f"{'+' if round(100 * value, d) > 0 else ''}{s} pp"
    if kind == "usd":
        return f"${value:,.{d}f}"
    if kind == "ci":
        return f"[{_num(value[0], d)}, {_num(value[1], d)}]"
    if kind == "pctci":  # an interval of a share, as a [low, high] list, in percent
        return f"[{_num(100 * value[0], d)}, {_num(100 * value[1], d)}]"
    if kind == "ppci":  # an interval of a difference, in percentage points
        lo, hi = (fmt(v, f"pp{d}").removesuffix(" pp") for v in value)
        return f"[{lo}, {hi}]"
    if kind == "pm":
        return f"{_num(value['mean'], d)} ± {_num(value['std'], d)}"
    if kind == "s":
        return f"{value:.{d}f} s"
    if kind == "dur":  # a duration in seconds, in the unit that reads best
        return _duration(value)
    raise ValueError(f"unknown format {spec!r}")


# --------------------------------------------------------------------------------------
# Values

_OPS = {
    ast.Add: operator.add,
    ast.Sub: operator.sub,
    ast.Mult: operator.mul,
    ast.Div: operator.truediv,
    ast.USub: operator.neg,
}
NAME = re.compile(r"[A-Za-z_][\w.]*")


def _eval(expr: str, env: dict[str, float]) -> float:
    """Arithmetic over named values only: + - * / and parentheses."""

    def walk(n: ast.AST) -> float:
        if isinstance(n, ast.Expression):
            return walk(n.body)
        if isinstance(n, ast.BinOp) and type(n.op) in _OPS:
            return _OPS[type(n.op)](walk(n.left), walk(n.right))
        if isinstance(n, ast.UnaryOp) and type(n.op) in _OPS:
            return _OPS[type(n.op)](walk(n.operand))
        if isinstance(n, ast.Constant) and isinstance(n.value, int | float):
            return n.value
        if isinstance(n, ast.Name):
            return env[n.id]
        raise ValueError(f"not allowed in expr: {ast.dump(n)}")

    return walk(ast.parse(expr.replace(".", "__"), mode="eval"))


def resolve_values(spec: dict) -> dict[str, str]:
    raw: dict[str, Any] = {}
    out: dict[str, str] = {}
    tbd: set[str] = set()  # pending values, and exprs over them
    todo = dict(spec.get("values") or {})
    while todo:
        progressed = False
        for name, v in list(todo.items()):
            if v.get("pending"):
                tbd.add(name)
            elif "expr" in v:
                deps = set(NAME.findall(v["expr"]))
                if not deps <= set(raw) | tbd:
                    continue
                if deps & tbd:
                    tbd.add(name)
                else:
                    env = {k.replace(".", "__"): raw[k] for k in deps}
                    raw[name] = _eval(v["expr"], env)
            elif "count_where" in v:  # items of a list (or values of a dict) matching all
                items = lookup(load(v["file"]), v["path"])
                items = items.values() if isinstance(items, dict) else items
                raw[name] = sum(
                    all(x.get(k) == want for k, want in v["count_where"].items()) for x in items
                )
            elif "sum_of" in v:  # sum of one field over a list, or a dict's values
                items = lookup(load(v["file"]), v["path"])
                items = items.values() if isinstance(items, dict) else items
                raw[name] = sum(lookup(x, v["sum_of"]) for x in items)
            elif "mean_of" in v:  # mean of one field over a list of records
                items = [lookup(x, v["mean_of"]) for x in lookup(load(v["file"]), v["path"])]
                raw[name] = sum(items) / len(items)
            else:
                raw[name] = lookup(load(v["file"]), v["path"])
            out[name] = TBD if name in tbd else fmt(raw[name], v["fmt"])
            del todo[name]
            progressed = True
        if not progressed:
            raise ValueError(f"unresolvable values (unknown names in expr?): {sorted(todo)}")
    return out


# --------------------------------------------------------------------------------------
# Tables: each a function returning Markdown built from results files, registered with
# @table and placed with {{table:<function name>}}.

TABLES: dict[str, Any] = {}


def table(fn):
    TABLES[fn.__name__] = fn
    return fn


def md(header: list[str], rows: list[list[str]], source: str) -> str:
    lines = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    lines += ["| " + " | ".join(r) + " |" for r in rows]
    return "\n".join(lines) + f"\n\n<sub>Source: {source}</sub>"


SECURITY_CATEGORIES = {
    "destructive": "Destructive statements",
    "multi_statement": "Several statements in one",
    "obfuscation": "Comment and unicode obfuscation",
    "catalog_snooping": "Catalog, file and network snooping",
    "confinement": "Another database's tables",
    "session": "Changing session settings",
    "resource_exhaustion": "Resource exhaustion",
    "prompt_injection": "What a planted instruction asks for",
}


@table
def security_suite() -> str:
    """Attacks per category, and how many each layer stopped on its own."""
    suite = load("metrics/security_suite.json")
    modes = ("parser", "database", "privileges")
    rows = []
    for key, label in SECURITY_CATEGORIES.items():
        recs = [r for r in suite["records"] if r["category"] == key]
        cells = []
        for mode in modes:
            outcomes = [r["modes"][mode]["outcome"] for r in recs]
            stopped = sum(o in ("rejected", "denied", "contained", "no_effect") for o in outcomes)
            shown = outcomes.count("disclosed")
            cells.append(f"{stopped}" + (f" (+{shown} names listed)" if shown else ""))
        rows.append([label, str(len(recs)), *cells])
    return md(
        [
            "Kind of attack",
            "Attacks",
            "Stopped by the checker alone",
            "By the database alone",
            "By the role's privileges alone",
        ],
        rows,
        "`results/metrics/security_suite.json` (one run)",
    )


MODELS = {
    "claude-sonnet-5": "Claude Sonnet 5",
    "claude-haiku-4-5": "Claude Haiku 4.5",
    "qwen2.5:3b-instruct": "Qwen2.5 3B (local)",
}
DESIGNS = {
    "d1": "1 single call, full schema",
    "d2": "2 + schema tools",
    "d3": "3 + self-correction",
    "d4": "4 + three-sample vote",
    "d5": "5 + schema narrowing",
}


def _iv(i: dict | None, spec: str, point: str) -> str:
    """An estimate with its interval, e.g. `59.3% [51.3, 67.3]`."""
    if not i or i.get("estimate") is None:
        return "–"
    return f"{fmt(i['estimate'], point)} {fmt(i, spec)}"


@table
def design_comparison() -> str:
    """Every design and model on the ablation set: accuracy, AURC, AUROC and cost."""
    runs = load("metrics/ablation.json")["runs"]
    rows = []
    for model, name in MODELS.items():
        for design, label in DESIGNS.items():
            s = runs.get(f"{model}/{design}")
            if s is None:
                continue
            cost = s["cost"]
            paid = cost["total_usd"] > 0
            rows.append(
                [
                    name,
                    label,
                    _iv(s["execution_accuracy"], "pctiv1", "pct1"),
                    fmt(s["selective"]["aurc"]["estimate"], "f3"),
                    fmt(s["calibration"]["auroc"]["estimate"], "f2"),
                    fmt(cost["per_question_usd"], "usd4") if paid else "free",
                    fmt(cost["per_correct_answer_usd"]["estimate"], "usd3") if paid else "free",
                ]
            )
    return md(
        [
            "Model",
            "Design",
            "Execution accuracy",
            "AURC (lower is better)",
            "AUROC",
            "Cost per question",
            "Cost per correct answer",
        ],
        rows,
        "`results/metrics/ablation.json` (one run per design and model; the ablation set, with "
        "evidence; batched calls at half price)",
    )


def _observed(pid: str, v: dict) -> str:
    """What a checked prediction found, in words and numbers."""
    iv = lambda x, s="pctiv1", p="pct1": _iv(x, s, p)  # noqa: E731
    if pid == "P01":
        return iv(v["execution_accuracy"])
    if pid == "P02":
        return f"design {v['best_ex_design'][1:]}, {iv(v['best_ex'])}"
    if pid == "P03":
        return f"design {v['winner'][1:]}"
    if pid == "P04":
        return iv(v["d4_minus_d3"], "ppiv1", "pp1")
    if pid == "P05":
        return "not applicable: the winner is design 1"
    if pid == "P06":
        return iv(v["raw_confidence_auroc_held_out"], "civ2", "f2")
    if pid == "P07":
        return iv(v["ece_platt_held_out"], "civ3", "f3")
    if pid == "P08":
        reached = "reached" if v["reached_target_on_calibration_split"] else "not reached"
        return (
            f"accuracy {iv(v['held_out_accuracy'])} at coverage {iv(v['held_out_coverage'])} "
            f"(target {reached} on the calibration split)"
        )
    if pid == "P09":
        return iv(v["haiku_minus_sonnet_d3"], "ppiv1", "pp1")
    if pid == "P10":
        return iv(v["execution_accuracy"])
    if pid == "P11":
        return iv(v["evidence_minus_no_evidence"], "ppiv1", "pp1")
    if pid == "P12":
        return (
            f"{iv(v['standard_and_multi_step_ex'])} against "
            f"{iv(v['held_out_benchmark_ex'])} on the held-out benchmark"
        )
    if pid == "P14":
        return f"{'adopted' if v['adopted'] else 'not adopted'}: {iv(v['gain'], 'ppiv1', 'pp1')}"
    if pid == "P15":
        verdict = "replaces" if v["replaces_own_loop"] else "does not replace"
        return (
            f"{verdict} the own loop: accuracy {iv(v['execution_accuracy'], 'ppiv1', 'pp1')}, "
            f"AURC {iv(v['aurc'], 'civ3', 'sf3')}"
        )
    if pid == "P13":
        return (
            f"ambiguous {iv(v['ambiguous'])}, unanswerable {iv(v['unanswerable'])}, "
            f"false premise {iv(v['false_premise'])}"
        )
    raise KeyError(pid)


@table
def predictions() -> str:
    """The pre-registered predictions checked so far, beside what was observed."""
    found: dict[str, dict] = {}
    for f in (
        "metrics/ablation.json",
        "metrics/benchmark_main.json",
        "metrics/own_set.json",
        "metrics/calibration.json",
        "metrics/escalation.json",
        "metrics/framework_comparison.json",
    ):
        found.update(load(f)["predictions"])
    rows = [
        [pid, v["claim"], v["prediction"], _observed(pid, v)] for pid, v in sorted(found.items())
    ]
    return md(
        ["", "Claim", "Predicted", "Observed"],
        rows,
        "`results/metrics/preregistration.md` (the predictions), `results/metrics/ablation.json`, "
        "`results/metrics/benchmark_main.json`, `results/metrics/own_set.json`, "
        "`results/metrics/calibration.json`, `results/metrics/escalation.json`, "
        "`results/metrics/framework_comparison.json` (one run each; intervals 95%)",
    )


GUARDRAIL_OBSERVED = {  # how each prediction's observed value is written
    "G1": "{} of 9",
    "G2": "{} of 51",
    "G4": "{} of 9",
    "G5": "{} of 9",
    "G7": "{} of 12 cells",
    "G8": "{} of 12 cells",
    "G9": "{} of 2",
}


@table
def guardrail_predictions() -> str:
    """The guardrail's pre-registered predictions beside what was observed."""
    rows = []
    for p in load("metrics/guardrail.json")["predictions"]:
        obs = p["observed"]
        if isinstance(obs, list):
            text = " / ".join(fmt(x, "pct0") for x in obs)
        elif p["id"] in GUARDRAIL_OBSERVED:
            text = GUARDRAIL_OBSERVED[p["id"]].format(obs)
        else:
            text = fmt(obs, "pct1")
        rows.append([p["id"], p["prediction"], p["range"], text, "held" if p["held"] else "missed"])
    return md(
        ["", "Prediction", "Predicted", "Observed", ""],
        rows,
        "`results/metrics/preregistration_phase7.md` (the predictions), "
        "`results/metrics/guardrail.json`, `results/metrics/planted_effects.json` (one run)",
    )


@table
def banking_causal() -> str:
    """The banking set's comparative and causal questions, before and after the guardrail."""
    rows = []
    for q in load("metrics/guardrail.json")["banking_f"]["per_question"]:
        a = q["after"]
        failed = a["failed_at"]
        ran = "yes" if a["ran_to_the_end"] else f"no ({failed['kind'] if failed else 'not run'})"
        rows.append(
            [
                q["id"],
                q["question"],
                "yes" if q["before"]["success"] else "no",
                ran,
                "yes" if a["success"] else "no",
                "yes" if a["reviewed_success"] else "no",
            ]
        )
    return md(
        ["", "Question", "Before", "Path ran", "After", "After, reviewed"],
        rows,
        "`results/metrics/guardrail.json`, `results/reviews/guardrail_review.yaml` (one run; "
        "reviewed by reading against each question's recorded check and the expert query's result)",
    )


@table
def promotion_rule() -> str:
    """The promotion rule's three conditions, as applied to the router."""
    d = load("registry/promotions.jsonl")[-1]["decision"]["checks"]
    ex, au, cost = (
        d["execution_accuracy_not_lower"],
        d["aurc_not_worse"],
        d["worst_case_question_cost"],
    )
    rows = [
        [
            "Execution accuracy, router minus baseline",
            f"lower bound at least {fmt(ex['required_at_least'], 'f0')}",
            f"{fmt(ex['difference'], 'pp1')}, lower bound {fmt(ex['lower_bound'], 'pp1')}",
            "met" if ex["passed"] else "not met",
        ],
        [
            "Area under the risk-coverage curve (lower is better), router minus baseline",
            f"upper bound at most {fmt(au['required_at_most'], 'f0')}",
            f"{fmt(au['difference'], 'sf3')}, upper bound {fmt(au['upper_bound'], 'sf3')}",
            "met" if au["passed"] else "not met",
        ],
        [
            "The most one question can cost the router",
            f"at most {fmt(cost['required_at_most'], 'usd2')}",
            fmt(cost["max_question_cost_usd"], "usd3"),
            "met" if cost["passed"] else "not met",
        ],
    ]
    return md(
        ["Condition", "Required", "Observed", ""],
        rows,
        "`results/registry/promotions.jsonl`, `configs/promotion.yaml` (one run, "
        "95% paired bootstrap intervals over the held-out questions)",
    )


@table
def drift_scenarios() -> str:
    """How the drift monitor reads sets it should and should not alarm on."""
    rows = []
    for label, r in load("metrics/drift_check.json")["systems"]["d1-sonnet-5"]["scenarios"].items():
        rows.append(
            [
                label.replace("held_out", "held-out"),
                fmt(r["psi"]["mean"], "f2"),
                fmt(r["share_of_windows_above_warn"], "pct0"),
                fmt(r["share_of_windows_above_alert"], "pct0"),
            ]
        )
    return md(
        ["Windows drawn from", "Index, mean", "Over the warning level", "Over the alert level"],
        rows,
        "`results/metrics/drift_check.json` (the baseline's own meter; one run of recorded "
        "answers, a window drawn with replacement; the synthetic rows are labeled as such)",
    )


@table
def load_test() -> str:
    """The replay service under load, by route and concurrency."""
    rows = [
        [
            r["route"],
            str(r["concurrency"]),
            fmt(r["p50_ms"], "f1"),
            fmt(r["p95_ms"], "f1"),
            fmt(r["p99_ms"], "f1"),
            fmt(r["requests_per_second"], "f0"),
            str(r["errors"]),
        ]
        for r in load("metrics/load_test.json")["results"]
    ]
    return md(
        ["Route", "Clients", "p50 (ms)", "p95 (ms)", "p99 (ms)", "Requests per second", "Errors"],
        rows,
        "`results/metrics/load_test.json` (one run on one laptop, the service in a container)",
    )


SANDBOX_CATEGORIES = {
    "network": "Reach the network or the host",
    "file_system": "Write, execute or read files",
    "privileges": "Gain privileges",
    "secrets": "Find secrets",
    "resources": "Exhaust time, memory, processes or output",
    "input": "Malformed or oversized input",
}


@table
def sandbox_attacks() -> str:
    """The sandbox's attacks per kind, and how each was stopped."""
    suite = load("metrics/sandbox_security.json")
    rows = []
    for key, label in SANDBOX_CATEGORIES.items():
        recs = [r for r in suite["records"] if r["category"] == key]
        outcomes = {}
        for r in recs:
            outcomes[r["outcome"]] = outcomes.get(r["outcome"], 0) + 1
        how = ", ".join(f"{n} {o}" for o, n in sorted(outcomes.items()))
        rows.append([label, str(len(recs)), str(sum(r["passed"] for r in recs)), how])
    return md(
        ["Kind of attack", "Attacks", "Blocked", "How"],
        rows,
        "`results/metrics/sandbox_security.json` (one run)",
    )


# --------------------------------------------------------------------------------------
# Checks


def typed_literals(template: Path) -> list[str]:
    spec = yaml.safe_load(VALUES.read_text(encoding="utf-8"))
    allowed = set(spec.get("allowed_literals") or [])
    text = PLACEHOLDER.sub("", template.read_text(encoding="utf-8"))
    text = re.sub(r"```.*?```", "", text, flags=re.S)
    text = re.sub(r"`[^`\n]*`", "", text)  # code spans: settings, versions, paths
    text = re.sub(r"\]\([^)]*\)", "]", text)  # link targets
    found = []
    for i, line in enumerate(text.splitlines(), 1):
        for m in LITERAL.finditer(line):
            if m.group(0) not in allowed:
                found.append(f"{template.name} line {i}: {m.group(0)!r} in: {line.strip()[:80]}")
    return found


def tables_without_source(text: str, name: str) -> list[str]:
    """Tables (runs of lines starting with `|`, outside code blocks) not followed, after
    any blank lines, by a line with `Source:` and something after it."""
    lines = text.splitlines()
    problems, i, in_code = [], 0, False
    while i < len(lines):
        if lines[i].lstrip().startswith("```"):
            in_code = not in_code
        elif not in_code and TABLE_ROW.match(lines[i]):
            start = i
            while i < len(lines) and TABLE_ROW.match(lines[i]):
                i += 1
            j = i
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j == len(lines) or not SOURCE_LINE.search(lines[j]):
                problems.append(f"{name} line {start + 1}: a table without a Source: line")
            continue
        i += 1
    return problems


# --------------------------------------------------------------------------------------


def render(template: Path, values: dict[str, str]) -> str:
    def sub(m: re.Match) -> str:
        name = m.group(1)
        if name.startswith("table:"):
            return TABLES[name.split(":", 1)[1]]()
        if name not in values:
            raise KeyError(f"{template.name}: {{{{{name}}}}} has no value in values.yaml")
        return values[name]

    return HEADER + PLACEHOLDER.sub(sub, template.read_text(encoding="utf-8"))


def render_all() -> dict[Path, str]:
    spec = yaml.safe_load(VALUES.read_text(encoding="utf-8"))
    values = resolve_values(spec)
    used = {n for t, _ in DOCS for n in PLACEHOLDER.findall(t.read_text(encoding="utf-8"))}
    in_exprs = {
        n for v in (spec.get("values") or {}).values() for n in NAME.findall(v.get("expr", ""))
    }
    unused = set(values) - used - in_exprs
    if unused:
        print(f"note: values defined but not used: {sorted(unused)}")
    pending = sorted(n for n, v in values.items() if v == TBD)
    if pending:
        print(f"note: {len(pending)} values pending (rendered TBD): {pending}")
    return {out: render(t, values) for t, out in DOCS}


def problems_in(rendered: dict[Path, str]) -> list[str]:
    found = [
        f"typed number (not from a results file): {x}" for t, _ in DOCS for x in typed_literals(t)
    ]
    found += [x for out, text in rendered.items() for x in tables_without_source(text, out.name)]
    return found


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered = render_all()
    problems = problems_in(rendered)
    if args.check:
        problems += [
            f"{out.name} differs from a fresh render: run scripts/90_readme.py"
            for out, text in rendered.items()
            if not out.exists() or out.read_text(encoding="utf-8") != text
        ]
        if problems:
            sys.exit("\n".join(problems))
        print("README.md and TECHNICAL_REPORT.md match the results files")
        return
    if problems:
        sys.exit("\n".join(problems))
    for out, text in rendered.items():
        out.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {out.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
